module.exports = {
  rules: {
    "no-statements-outside-pipe": require("./rules/no-statements-outside-pipe"),
    "prefer-flatmap-over-chain": require("./rules/prefer-flatmap-over-chain"),
    "no-nested-pipes": require("./rules/no-nested-pipes"),
    "no-const-variables": require("./rules/no-const-variables"),
    "no-async-await": require("./rules/no-async-await"),
    "prefer-a-map": require("./rules/prefer-a-map"),
    "no-long-inline-functions-in-pipe": require("./rules/no-long-inline-functions-in-pipe"),
    "enforce-file-layout": require("./rules/enforce-file-layout"),
    "no-pipe-in-brackets": require("./rules/no-pipe-in-brackets"),
    "no-fp-ts-lib-imports": require("./rules/no-fp-ts-lib-imports"),
    "prefer-concise-arrow-function": require("./rules/prefer-concise-arrow-function"),
    "prefer-merged-short-pipes": require("./rules/prefer-merged-short-pipes"),
    "no-unnecessary-currying": require("./rules/no-unnecessary-currying"),
    "prefer-grouped-parameters": require("./rules/prefer-grouped-parameters"),
    "simplify-task-constructors": require("./rules/simplify-task-constructors"),
  },
  configs: {
    recommended: {
      rules: {
        "fpts-style/no-statements-outside-pipe": "error",
        "fpts-style/prefer-flatmap-over-chain": "error",
        "fpts-style/no-nested-pipes": "error",
        "fpts-style/no-async-await": "error",
        "fpts-style/prefer-a-map": "error",
        "fpts-style/no-long-inline-functions-in-pipe": ["error", { maxLines: 5 }],
        "fpts-style/enforce-file-layout": "error",
        "fpts-style/no-pipe-in-brackets": "error",
        "fpts-style/no-fp-ts-lib-imports": "error",
        "fpts-style/no-const-variables": "warn",
        "fpts-style/prefer-concise-arrow-function": "error",
        "fpts-style/prefer-merged-short-pipes": "warn",
        "fpts-style/no-unnecessary-currying": "warn",
        "fpts-style/prefer-grouped-parameters": "warn",
        "fpts-style/simplify-task-constructors": "error",
      },
    },
  },
}
