#!/bin/bash

set -e
exec 1>&2

function check_todo() {
  TODO_REGEX='// TODO'
  FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ts" | tr '\n' ' ')
  if [ -n "$FILES" ]; then
      # Check for the TODO_REGEX in each staged .ts file
      for FILE in $FILES; do
          if grep -q "$TODO_REGEX" "$FILE"; then
              echo "ERROR: Found 'TODO' reference in $FILE"
              echo "Please remove 'TODO' comments before committing."
              exit 1
          fi
      done
  fi
}

function check_committer() {
  COMMITTER_NAME=$(git config user.name)
  if [ "$COMMITTER_NAME" != "tonisives" ]; then
    echo "not tonisives"
    exit 1
  fi
}

function build_dist() {
  rm -rf dist
  yarn test
  yarn build
  git add dist
}

check_committer
check_todo
build_dist